name: Build and Test

"on":
    push:
        branches:
            - main
    pull_request: null

permissions:
    contents: read

jobs:
    build-and-test:
        runs-on: '${{ matrix.os }}'
        strategy:

            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v4
            -
                name: Install Coreutils (macOS only)
                if: matrix.os == 'macos-latest'
                run: brew install coreutils
            -
                name: Build
                shell: bash
                run: make
            -
                name: Run test suite
                shell: bash
                run: bash tests/run.sh
