name: REPL Build and Test

"on":
    push:
        branches:
            - main
        paths:
            - "cli/**"
    pull_request:
        paths:
            - "cli/**"

permissions:
    contents: read

jobs:
    repl-test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Build and Test REPL
                working-directory: cli
                shell: bash
                run: |
                    python3 -m pip install --quiet pyte wcwidth
                    
                    sed -i.bak 's/"\${extra_args\[@\]}"/${extra_args[@]+"${extra_args[@]}"}/g' tests/run.sh
                    chmod +x build.sh run_tests.sh
                    ./build.sh
                    ./run_tests.sh
